### ISSUE TITLE
Stolen code

### ISSUE THREAD

**Issue by BlackChakra167** [AldoRmzCode/wargardenz.io#4]
Attention all viewers 
This is stolen code from Coder Gautam and his game Swordbattle.io. 
Please go to his GitHub to see the true game.
[https://github.com/codergautam](url) [sword battle.io](url) 

Atención a todos los espectadores
Este es un código robado de Coder Gautam y su juego Swordbattle.io.
Vaya a su GitHub para ver el verdadero juego.
[https://github.com/codergautam](url) [sword battle.io](url)

**Comment by Jaredass** [comment]
> Attention all viewers This is stolen code from Coder Gautam and his game Swordbattle.io. Please go to his GitHub to see the true game. [https://github.com/codergautam](url) [sword battle.io](url)
> 
> Atención a todos los espectadores Este es un código robado de Coder Gautam y su juego Swordbattle.io. Vaya a su GitHub para ver el verdadero juego. [https://github.com/codergautam](url) [sword battle.io](url)

the code is open source and was not stolen

**Comment by AldoRmzCode** [comment]
In the commit "more credits 2", "ecc77ce5c689d196b05ee9a1320a52ff9055df49" made on November 13, 2022 the corresponding credits were given, I communicated with him personally and even his name is in the "README". 
It should be clarified that it is open source and has a valid license that supports general uses.
Besides that it has not been for profit.

<<<Add more information about the problem(s) or conflict(s) in order to correct it and improve it.>>>

sorry for any confusion
thank you very much!


resourses:
https://github.com/AldoRmzCode/wargardenz.io/commit/ecc77ce5c689d196b05ee9a1320a52ff9055df49
https://github.com/AldoRmzCode/wargardenz.io/commit/a951e5041b995b158dce48be4f54e88570e0360e

**Comment by AldoRmzCode** [comment]
> Atención a todos los espectadores Este es un código robado de Coder Gautam y su juego Swordbattle.io. Vaya a su GitHub para ver el verdadero juego. [https://github.com/codergautam ](url) [batalla de espadas.io](url)
> 
> Atención a todos los espectadores Este es un código robado de Coder Gautam y su juego Swordbattle.io. Vaya a su GitHub para ver el verdadero juego. [https://github.com/codergautam ](url) [batalla de espadas.io](url)
